#/bin/sh
openscad -o stl/y_belt_idler_2.stl y_belt_idler_2.scad
openscad -o stl/y_belt_idler_1.stl y_belt_idler_1.scad
openscad -o stl/y_motor.stl y_motor.scad
openscad -o stl/equerre3.stl equerre3.scad
openscad -o stl/support_tige8_y.stl support_tige8_y.scad
openscad -o stl/y_lm8uu.stl y_lm8uu.scad
openscad -o stl/y_belt_holder.stl y_belt_holder.scad
openscad -o stl/molette_m5.stl molette_m5.scad
openscad -o stl/omega3.stl omega3.scad
openscad -o stl/cache.stl cache.scad
openscad -o stl/equerre4.stl equerre4.scad
openscad -o stl/spool_rondelle.stl spool_rondelle.scad
openscad -o stl/spool_holder.stl spool_holder.scad
openscad -o stl/molette_m6.stl molette_m6.scad
openscad -o stl/x_carriage.stl x_carriage.scad
openscad -o stl/z_axis_bottom.stl z_axis_bottom.scad
openscad -o stl/z_axis_top.stl z_axis_top.scad
openscad -o stl/sensor_holder.stl sensor_holder.scad
